<?php

namespace CarRentalBundle\Repository;

/**
 * RentalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RentalRepository extends \Doctrine\ORM\EntityRepository
{
}
