car_rental_homepage:
    path:     /
    defaults: { _controller: CarRentalBundle:Car:index }

index:
    path:     /
    defaults: { _controller: CarRentalBundle:Car:index }

show:
    path:     /car/{id}
    defaults: { _controller: CarRentalBundle:Car:show }

rent:
    path:     /rent/{id}
    defaults: { _controller: CarRentalBundle:Car:rent }

create:
    path:     /create/{name}/{type}/{color}/{horsepower}/{photo}
    defaults: { _controller: CarRentalBundle:Car:create }

index:
    path:     /
    defaults: { _controller: CarRentalBundle:Rental:index }

show:
    path:     /show
    defaults: { _controller: CarRentalBundle:Rental:show }

review:
    path:     /review
    defaults: { _controller: CarRentalBundle:Rental:review }
